# Dependencies 
markdown:	  redcarpet
highlighter:	  pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matt Giamou
tagline:          Matt Giamou’s Webpage
url:              http://mattgiamou.github.io
paginate:         1
baseurl:          http://mattgiamou.github.io/mattgiamou.github.io/

author:
  name:           Matt Giamou
  url:            https://twitter.com/mattgiamou
