# General settings
title: Matt Giamou
title_html: "<b>matt</b>hew<b><span class=\"invisible\"> </span>Giamou</b>"
description: Matt is a PhD student working on robotic navigation and motion planning.
baseurl: ""
url: "mattgiamou.github.io" 

# langs: ["fr", "en"]
# defaults:
#   - scope:
#       path: ""
#     values:
#       lang: "fr"

# Author
author: Matt Giamou

email: matt.giamou@gmail.com
twitter_username: mattgiamou
github_username: mattgiamou
linkedin_username: matthew-giamou
curriculum:
  name: cv
  url: assets/giamou_cv.pdf

# Nav menu
# nav_ext_links:
#   - name: Blog
#     url:
#       fr: https://sociologs.com/fr/
#       en: https://sociologs.com/en/


# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
# markdown: redcarpet
# redcarpet:
#   extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes", "with_toc_data"]
markdown: kramdown
# theme: midnight
remote-theme: gaalcaraz/academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
