---
title: "The Rolling Coins Problem"
author: "Matt Giamou"
date: "01/05/2024"
format:
  html:
    code-fold: true
    mainfont: "Computer Modern"
jupyter: julia-1.9
---

## The Problem

Consider a coin of radius $r$ rolling (without slipping) along the circumference of another coin of radius $R$. Let $\theta$ be the angle describing the coin with radius $r$'s progress along the other coin's circumference, and let $\phi$ be the angle describing the orientation of the coin with radius $r$. The initial configuration corresponding to $\theta = \phi = 0$ is shown in @fig-test. **What is the relationship between $\theta$ and $\phi$?**

## Solution

The key to solving this problem is recognizing that our intuitive description of slip-free rolling on a flat surface needs modification. For a coin of radius $r$ rolling on a flat surface, we know that the distance travelled is 

$$
d = \phi r. 
$$ {#eq-flat}

Extrapolating this to the case of two coins suggests that the kinematic equation for the system is simply 

$$
\phi r = \theta R,
$$

but this does not account for the curvature of coin with radius $R$. To make use of the principle in @eq-flat, we need to consider a *contact* reference frame $c$ which rotates with $\theta$ and is described by the transformation matrix

$$
T^w_c(\theta) = \begin{bmatrix}
\cos \theta & -\sin \theta & R \cos \theta \\ 
\sin \theta & \cos \theta & R \sin \theta \\
0 & 0 & 1
\end{bmatrix} \in \mathrm{SE}(2),
$$
where $w$ is the base frame fixed to the pose of the coin with radius $R$. In frame $c$, the slip-free rolling condition is described by the transformation between the *local* frame $l$ fixed to the coin with radius $r$ as a function of $\theta$:
$$
T^c_l(\theta) = \begin{bmatrix}
\cos(\frac{\theta R}{r}) & -\sin(\frac{\theta R}{r}) & r \\ 
\sin(\frac{\theta R}{r}) & \cos(\frac{\theta R}{r}) & 0 \\
0 & 0 & 1
\end{bmatrix} \in \mathrm{SE}(2).
$$

The overall kinematic equation describing the evolution of the pose of the coin with radius $r$ with respect to $w$ is therefore 

$$
T^w_l(\theta) = T^w_c(\theta) T^c_l(\theta), 
$$
which by the additivity of 2D rotations tells us that the sought-after orientation $\phi$ of the frame $l$ is governed by
$$
\phi = \theta(1 + \frac{R}{r}).
$$

This shows that in addition to the term $\theta \frac{R}{r}$ that describes rolling on a flat surface, the curvature of the contact surface introduces another term that rotates proportionately with $\theta$. 

## Insights 
Why do I think this formal kinematic description of the problem is important? In contrast with intuitive descriptions of the solution (which is easy to demonstrate at home with any pair of circular objects), it highlights a principled strategy for solving generalized problems of this form. Perhaps we are interested in how a coin revolves on an arbitrary smooth curve of the form 

$$
f(x, y) = 0,
$$
which generalizes the circular case ($f(x, y) = x^2 + y^2 - R^2$) quite neatly.

```{julia}
#| label: fig-test
#| fig-cap: "Testing out the plotting functionality."

using Plots

plot(1:3, 2:4)

```